#!/bin/bash
echo "" #gap between log entries
date -u #prints the date out for the log

#move yesterday's outputs to the archive
yesterday=$(date -u --date="yesterday" +'%Y%m%d') #yesterday's date in utc
mkdir zARCHIVE/${yesterday} #makes folder for yesterday's outputs in archive
mv xOUTPUTS/* zARCHIVE/${yesterday} #moves outputs to the folder
mv zARCHIVE/${yesterday}/tns_public_objects.csv xOUTPUTS
mv zARCHIVE/${yesterday}/observations.json xOUTPUTS #move these back as they are always updated

homedir=$(pwd) #the home directory to return to once module is finished

### BILLY ###
cd ${homedir}/BILLY
python tns_update.py #run python script to update the local TNS database
cd ${homedir}

### LUCY ###
cd ${homedir}/LUCY
python pscores.py #make the new priorty score lists
cd ${homedir}

### MR. KITE ###
cd ${homedir}/MR_KITE
python attachments.py #make the email attachments
python email_alert.py #send the email alert
cd ${homedir}

### RITA ###
cd ${homedir}/RITA
python followup.py #request observations from LT
pyhton dummy-trigger.py
