#!/bin/bash

#line between log entries
echo "" ; echo "-----------------------------------------------------" ; echo ""
homedir=$(pwd) #the home directory to return to once module is finished

#delay until UTC midnight if runs before
python delay.py

#yesterday's date in utc
date -u #prints the date out for the log
yesterday=$(date -u --date="yesterday" +'%Y%m%d')
ydDIR="zARCHIVE/${yesterday}"

# makes folder for yesterday's outputs in archive and move them there
mkdir zARCHIVE/${yesterday}
mv xOUTPUTS/* zARCHIVE/${yesterday}
#move these back as they are live documents
mv zARCHIVE/${yesterday}/tns_public_objects.csv xOUTPUTS
mv zARCHIVE/${yesterday}/request_records.json xOUTPUTS
mv zARCHIVE/${yesterday}/observations.csv xOUTPUTS
#remove file indicating that LT connection failed (if exists)
rm ${homedir}/RITA/fail.txt

### BILLY ###
cd ${homedir}/BILLY
python tns_update.py #run python script to update the local TNS database
cd ${homedir}

### LUCY ###
cd ${homedir}/LUCY
python pscores.py #make the new priority score lists
cd ${homedir}

### MR. KITE ###
cd ${homedir}/MR_KITE
python email_alert.py #send the email alert
cd ${homedir}

### RITA 1 ###
cd ${homedir}/RITA
python requestA.py #request 2nd set of observations from LT for this night
python obs_check.py #check if targets requested were observed
cd ${homedir}

### MR. KITE 2 ###
cd ${homedir}/MR_KITE
python obs_alert.py #send the observations alert email
cd ${homedir}

### RITA 2 ###
cd ${homedir}/RITA
python requestB.py #request 1st set of observations from LT for next night

### SGT. P ###
cd ${homedir}/SGT_P
python auto_dload.py #downloads new obs data from LT archive
